name: Build Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set environment variables
        run: |
          echo "IMAGE_VERSION=1.0.0-alpha.$(date -u -Iseconds | sed 's/[+].*//' | sed 's/[^0-9]//g')" >> $GITHUB_ENV
          echo "IMAGE_TAG=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
          echo "CONTAINER_ARCH=${{ vars.CONTAINER_ARCH }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.9.1
          driver: docker-container
          use: true
          platforms: ${{ env.CONTAINER_ARCH }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          push: true
          platforms: ${{ env.CONTAINER_ARCH }}
          tags: ${{ env.IMAGE_TAG }}:latest,${{ env.IMAGE_TAG }}:${{ env.IMAGE_VERSION }}
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
